export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const CHECK_AUTH = 'checkAuth'
// account actions
export const GET_STATE_ACCOUNTS = 'getStateAccounts'
export const GET_ACCOUNTS = 'getAccounts'
export const GET_ACCOUNT = 'getAccount'
export const CREATE_ACCOUNT = 'createAccount'
export const UPDATE_ACCOUNT = 'updateAccount'
export const DELETE_ACCOUNT = 'deleteAccount'
export const SEARCH_ACCOUNTS = 'searchAccounts'
export const GET_EMPLOYEES_NO_ACCOUNT = 'getEmployeesNoAccount'
export const GET_ROLEGROUP_OF_ACCOUNT = 'getRoleGroupOfAccount'
// employee actions
export const GET_STATE_EMPLOYEES = 'getStateEmployees'
export const GET_EMPLOYEES = 'getEmployees'
export const SEARCH_EMPLOYEES = 'searchEmployees'
export const SORT_EMPLOYEES = 'sortEmployees'
export const GET_EMPLOYEE = 'getEmployee'
export const CREATE_EMPLOYEE = 'createEmployee'
export const UPDATE_EMPLOYEE = 'updateEmployee'
export const DELETE_EMPLOYEE = 'deleteEmployee'
// paymentmethod actions
export const GET_STATE_PAYMENTMETHODS = 'getStatePaymentMethods'
export const GET_PAYMENTMETHODS = 'getPaymentMethods'
export const SEARCH_PAYMENTMETHODS = 'searchPaymentMethods'
export const SORT_PAYMENTMETHODS = 'sortPaymentMethods'
export const GET_PAYMENTMETHOD = 'getPaymentMethod'
export const CREATE_PAYMENTMETHOD = 'createPaymentMethod'
export const UPDATE_PAYMENTMETHOD = 'updatePaymentMethod'
export const DELETE_PAYMENTMETHOD = 'deletePaymentMethod'
// product actions
export const GET_STATE_PRODUCTS = 'getStateProducts'
export const GET_PRODUCTS = 'getProducts'
export const SEARCH_PRODUCTS = 'searchProducts'
export const SORT_PRODUCTS = 'sortProducts'
export const GET_PRODUCT = 'getProduct'
export const CREATE_PRODUCT = 'createProduct'
export const UPDATE_PRODUCT = 'updateProduct'
export const DELETE_PRODUCT = 'deleteProduct'
// productcategory actions
export const GET_STATE_PRODUCTCATEGORYS = 'getStateProductCategorys'
export const GET_PRODUCTCATEGORYS = 'getProductCategorys'
export const SEARCH_PRODUCTCATEGORYS = 'searchProductCategorys'
export const SORT_PRODUCTCATEGORYS = 'sortProductCategorys'
export const GET_PRODUCTCATEGORY = 'getProductCategory'
export const CREATE_PRODUCTCATEGORY = 'createProductCategory'
export const UPDATE_PRODUCTCATEGORY = 'updateProductCategory'
export const DELETE_PRODUCTCATEGORY = 'deleteProductCategory'
// payment actions
export const GET_STATE_PAYMENTS = 'getStatePayments'
export const GET_PAYMENTS = 'getPayments'
export const SEARCH_PAYMENTS = 'searchPayments'
export const SORT_PAYMENTS = 'sortPayments'
export const GET_PAYMENT = 'getPayment'
export const CREATE_PAYMENT = 'createPayment'
export const UPDATE_PAYMENT = 'updatePayment'
export const DELETE_PAYMENT = 'deletePayment'
// brand actions
export const GET_STATE_BRANDS = 'getStateBrands'
export const GET_BRANDS = 'getBrands'
export const SEARCH_BRANDS = 'searchBrands'
export const SORT_BRANDS = 'sortBrands'
export const GET_BRAND = 'getBrand'
export const CREATE_BRAND = 'createBrand'
export const UPDATE_BRAND = 'updateBrand'
export const DELETE_BRAND = 'deleteBrand'
// productunit actions
export const GET_STATE_PRODUCTUNITS = 'getStateProductUnits'
export const GET_PRODUCTUNITS = 'getProductUnits'
export const SEARCH_PRODUCTUNITS = 'searchProductUnits'
export const SORT_PRODUCTUNITS = 'sortProductUnits'
export const GET_PRODUCTUNIT = 'getProductUnit'
export const CREATE_PRODUCTUNIT = 'createProductUnit'
export const UPDATE_PRODUCTUNIT = 'updateProductUnit'
export const DELETE_PRODUCTUNIT = 'deleteProductUnit'
// productvariant actions
export const GET_STATE_PRODUCTVARIANTS = 'getStateProductVariants'
export const GET_PRODUCTVARIANTS = 'getProductVariants'
export const SEARCH_PRODUCTVARIANTS = 'searchProductVariants'
export const SORT_PRODUCTVARIANTS = 'sortProductVariants'
export const GET_PRODUCTVARIANT = 'getProductVariant'
export const CREATE_PRODUCTVARIANT = 'createProductVariant'
export const UPDATE_PRODUCTVARIANT = 'updateProductVariant'
export const DELETE_PRODUCTVARIANT = 'deleteProductVariant'
// department actions
export const GET_STATE_DEPARTMENTS = 'getStateDepartments'
export const GET_DEPARTMENTS = 'getDepartments'
export const SEARCH_DEPARTMENTS = 'searchDepartments'
export const SORT_DEPARTMENTS = 'sortDepartments'
export const GET_DEPARTMENT = 'getDepartment'
export const CREATE_DEPARTMENT = 'createDepartment'
export const UPDATE_DEPARTMENT = 'updateDepartment'
export const DELETE_DEPARTMENT = 'deleteDepartment'
// order actions
export const GET_STATE_ORDERS = 'getStateOrders'
export const GET_ORDERS = 'getOrders'
export const SEARCH_ORDERS = 'searchOrders'
export const SORT_ORDERS = 'sortOrders'
export const GET_ORDER = 'getOrder'
export const CREATE_ORDER = 'createOrder'
export const UPDATE_ORDER = 'updateOrder'
export const DELETE_ORDER = 'deleteOrder'
// orderitem actions
export const GET_STATE_ORDERITEMS = 'getStateOrderItems'
export const GET_ORDERITEMS = 'getOrderItems'
export const SEARCH_ORDERITEMS = 'searchOrderItems'
export const SORT_ORDERITEMS = 'sortOrderItems'
export const GET_ORDERITEM = 'getOrderItem'
export const CREATE_ORDERITEM = 'createOrderItem'
export const UPDATE_ORDERITEM = 'updateOrderItem'
export const DELETE_ORDERITEM = 'deleteOrderItem'
// member actions
export const GET_STATE_MEMBERS = 'getStateMembers'
export const GET_MEMBERS = 'getMembers'
export const SEARCH_MEMBERS = 'searchMembers'
export const SORT_MEMBERS = 'sortMembers'
export const GET_MEMBER = 'getMember'
export const CREATE_MEMBER = 'createMember'
export const UPDATE_MEMBER = 'updateMember'
export const DELETE_MEMBER = 'deleteMember'
// shift actions
export const GET_STATE_SHIFTS = 'getStateShifts'
export const GET_SHIFTS = 'getShifts'
export const SEARCH_SHIFTS = 'searchShifts'
export const SORT_SHIFTS = 'sortShifts'
export const GET_SHIFT = 'getShift'
export const CREATE_SHIFT = 'createShift'
export const UPDATE_SHIFT = 'updateShift'
export const DELETE_SHIFT = 'deleteShift'
// cashup actions
export const GET_STATE_CASHUPS = 'getStateCashUps'
export const GET_CASHUPS = 'getCashUps'
export const SEARCH_CASHUPS = 'searchCashUps'
export const SORT_CASHUPS = 'sortCashUps'
export const GET_CASHUP = 'getCashUp'
export const CREATE_CASHUP = 'createCashUp'
export const UPDATE_CASHUP = 'updateCashUp'
export const DELETE_CASHUP = 'deleteCashUp'
// cashupitem actions
export const GET_STATE_CASHUPITEMS = 'getStateCashUpItems'
export const GET_CASHUPITEMS = 'getCashUpItems'
export const SEARCH_CASHUPITEMS = 'searchCashUpItems'
export const SORT_CASHUPITEMS = 'sortCashUpItems'
export const GET_CASHUPITEM = 'getCashUpItem'
export const CREATE_CASHUPITEM = 'createCashUpItem'
export const UPDATE_CASHUPITEM = 'updateCashUpItem'
export const DELETE_CASHUPITEM = 'deleteCashUpItem'
// employeeitemshift actions
export const GET_STATE_EMPLOYEEITEMSHIFTS = 'getStateEmployeeItemShifts'
export const GET_EMPLOYEEITEMSHIFTS = 'getEmployeeItemShifts'
export const SEARCH_EMPLOYEEITEMSHIFTS = 'searchEmployeeItemShifts'
export const SORT_EMPLOYEEITEMSHIFTS = 'sortEmployeeItemShifts'
export const GET_EMPLOYEEITEMSHIFT = 'getEmployeeItemShift'
export const CREATE_EMPLOYEEITEMSHIFT = 'createEmployeeItemShift'
export const UPDATE_EMPLOYEEITEMSHIFT = 'updateEmployeeItemShift'
export const DELETE_EMPLOYEEITEMSHIFT = 'deleteEmployeeItemShift'

// purchase actions
export const GET_STATE_PURCHASES = 'getStatePurchases'
export const GET_ALL_PURCHASE_COUNT = 'getStatePurchaseCount'
export const GET_PURCHASES = 'getPurchases'
export const SEARCH_PURCHASES = 'searchPurchases'
export const SORT_PURCHASES = 'sortPurchases'
export const GET_PURCHASE = 'getPurchase'
export const CREATE_PURCHASE = 'createPurchase'
export const CREATE_APPROVE_PURCHASE = 'createApprovePurchase'
export const UPDATE_PURCHASE = 'updatePurchase'
export const DELETE_PURCHASE = 'deletePurchase'

// purchase actions
export const GET_STATE_PURCHASEORDERS = 'getStatePurchaseOrders'
export const GET_ALL_PURCHASEORDER_COUNT = 'getStatePurchaseOrderCount'
export const GET_PURCHASEORDERS = 'getPurchaseOrders'
export const SEARCH_PURCHASEORDERS = 'searchPurchaseOrders'
export const SORT_PURCHASEORDERS = 'sortPurchaseOrders'
export const GET_PURCHASEORDER = 'getPurchaseOrder'
export const CREATE_PURCHASEORDER = 'createPurchaseOrder'
export const CREATE_APPROVE_PURCHASEORDER = 'createApprovePurchaseOrder'
export const UPDATE_PURCHASEORDER = 'updatePurchaseOrder'
export const DELETE_PURCHASEORDER = 'deletePurchaseOrder'

// purchase actions
export const GET_STATE_STOCKADJUSTMENTS = 'getStateStockAdjustments'
export const GET_ALL_STOCKADJUSTMENT_COUNT = 'getStateStockAdjustmentCount'
export const GET_STOCKADJUSTMENTS = 'getStockAdjustments'
export const SEARCH_STOCKADJUSTMENTS = 'searchStockAdjustments'
export const SORT_STOCKADJUSTMENTS = 'sortStockAdjustments'
export const GET_STOCKADJUSTMENT = 'getStockAdjustment'
export const CREATE_STOCKADJUSTMENT = 'createStockAdjustment'
export const CREATE_APPROVE_STOCKADJUSTMENT = 'createApproveStockAdjustment'
export const UPDATE_STOCKADJUSTMENT = 'updateStockAdjustment'
export const DELETE_STOCKADJUSTMENT = 'deleteStockAdjustment'
export const UPDATE_APPROVE_STOCKADJUSTMENT = 'updateApproveStockAdjustment'
export const CANCEL_STOCKADJUSTMENT = 'cancelStockAdjustment'

// purchase actions
export const GET_STATE_PRICELISTS = 'getStatePriceLists'
export const GET_PRICELISTS = 'getPriceLists'
export const SEARCH_PRICELISTS = 'searchPriceLists'
export const SORT_PRICELISTS = 'sortPriceLists'
export const GET_PRICELIST = 'getPriceList'
export const CREATE_PRICELIST = 'createPriceList'
export const CREATE_APPROVE_PRICELIST = 'createApprovePriceList'
export const UPDATE_PRICELIST = 'updatePriceList'
export const DELETE_PRICELIST = 'deletePriceList'

// purchase actions
export const GET_STATE_PURCHASES_RETUR = 'getStatePurchasesRetur'
export const GET_PURCHASES_RETUR = 'getPurchasereturs'
export const SEARCH_PURCHASES_RETUR = 'searchPurchasereturs'
export const SORT_PURCHASES_RETUR = 'sortPurchasereturs'
export const GET_PURCHASE_RETUR = 'getPurchaseretur'
export const CREATE_PURCHASE_RETUR = 'createPurchaseretur'
export const CREATE_APPROVE_PURCHASE_RETUR = 'createApprovePurchaseretur'
export const UPDATE_PURCHASE_RETUR = 'updatePurchaseretur'
export const DELETE_PURCHASE_RETUR = 'deletePurchaseretur'
// purchaseitem actions
export const GET_STATE_PURCHASEITEMS = 'getStatePurchaseItems'
export const GET_PURCHASEITEMS = 'getPurchaseItems'
export const SEARCH_PURCHASEITEMS = 'searchPurchaseItems'
export const SORT_PURCHASEITEMS = 'sortPurchaseItems'
export const GET_PURCHASEITEM = 'getPurchaseItem'
export const CREATE_PURCHASEITEM = 'createPurchaseItem'
export const UPDATE_PURCHASEITEM = 'updatePurchaseItem'
export const DELETE_PURCHASEITEM = 'deletePurchaseItem'
// supplier actions
export const GET_STATE_SUPPLIERS = 'getStateSuppliers'
export const GET_SUPPLIERS = 'getSuppliers'
export const SEARCH_SUPPLIERS = 'searchSuppliers'
export const SORT_SUPPLIERS = 'sortSuppliers'
export const GET_SUPPLIER = 'getSupplier'
export const CREATE_SUPPLIER = 'createSupplier'
export const UPDATE_SUPPLIER = 'updateSupplier'
export const DELETE_SUPPLIER = 'deleteSupplier'
// warehouse actions
export const GET_STATE_WAREHOUSES = 'getStateWarehouses'
export const GET_WAREHOUSES = 'getWarehouses'
export const SEARCH_WAREHOUSES = 'searchWarehouses'
export const SORT_WAREHOUSES = 'sortWarehouses'
export const GET_WAREHOUSE = 'getWarehouse'
export const CREATE_WAREHOUSE = 'createWarehouse'
export const UPDATE_WAREHOUSE = 'updateWarehouse'
export const DELETE_WAREHOUSE = 'deleteWarehouse'
// warehousetype actions
export const GET_STATE_WAREHOUSETYPES = 'getStateWarehouseTypes'
export const GET_WAREHOUSETYPES = 'getWarehouseTypes'
export const SEARCH_WAREHOUSETYPES = 'searchWarehouseTypes'
export const SORT_WAREHOUSETYPES = 'sortWarehouseTypes'
export const GET_WAREHOUSETYPE = 'getWarehouseType'
export const CREATE_WAREHOUSETYPE = 'createWarehouseType'
export const UPDATE_WAREHOUSETYPE = 'updateWarehouseType'
export const DELETE_WAREHOUSETYPE = 'deleteWarehouseType'
// tax actions
export const GET_STATE_TAXS = 'getStateTaxs'
export const GET_TAXS = 'getTaxs'
export const SEARCH_TAXS = 'searchTaxs'
export const SORT_TAXS = 'sortTaxs'
export const GET_TAX = 'getTax'
export const CREATE_TAX = 'createTax'
export const UPDATE_TAX = 'updateTax'
export const DELETE_TAX = 'deleteTax'
// paymentterm actions
export const GET_STATE_PAYMENTTERMS = 'getStatePaymentTerms'
export const GET_PAYMENTTERMS = 'getPaymentTerms'
export const SEARCH_PAYMENTTERMS = 'searchPaymentTerms'
export const SORT_PAYMENTTERMS = 'sortPaymentTerms'
export const GET_PAYMENTTERM = 'getPaymentTerm'
export const CREATE_PAYMENTTERM = 'createPaymentTerm'
export const UPDATE_PAYMENTTERM = 'updatePaymentTerm'
export const DELETE_PAYMENTTERM = 'deletePaymentTerm'
// unit actions
export const GET_STATE_UNITS = 'getStateUnits'
export const GET_UNITS = 'getUnits'
export const SEARCH_UNITS = 'searchUnits'
export const SORT_UNITS = 'sortUnits'
export const GET_UNIT = 'getUnit'
export const CREATE_UNIT = 'createUnit'
export const UPDATE_UNIT = 'updateUnit'
export const DELETE_UNIT = 'deleteUnit'
// stockmovement actions
export const GET_STATE_STOCKMOVEMENTS = 'getStateStockMovements'
export const GET_STOCKMOVEMENTS = 'getStockMovements'
export const SEARCH_STOCKMOVEMENTS = 'searchStockMovements'
export const SORT_STOCKMOVEMENTS = 'sortStockMovements'
export const GET_STOCKMOVEMENT = 'getStockMovement'
export const CREATE_STOCKMOVEMENT = 'createStockMovement'
export const UPDATE_STOCKMOVEMENT = 'updateStockMovement'
export const DELETE_STOCKMOVEMENT = 'deleteStockMovement'
// stock actions
export const GET_STATE_STOCKS = 'getStateStocks'
export const GET_STOCKS = 'getStocks'
export const SEARCH_STOCKS = 'searchStocks'
export const SORT_STOCKS = 'sortStocks'
export const GET_STOCK = 'getStock'
export const CREATE_STOCK = 'createStock'
export const UPDATE_STOCK = 'updateStock'
export const DELETE_STOCK = 'deleteStock'
// goodreceipt action
export const GET_STATE_GOODSRECEIPTS = 'getStateGoodsReceipt'
export const CREATE_APPROVE_GOODSRECEIPT = 'createApproveGoodsReceipt'
export const GET_GOODSRECEIPT = 'getGoodsReceipt'
export const GET_GOODSRECEIPTS = 'getGoodsReceipts'
export const SEARCH_GOODSRECEIPT = 'searchGoodsReceipt'
export const SORT_GOODSRECEIPT = 'sortGoodsReceipt'
export const CREATE_GOODSRECEIPT = 'createGoodsReceipt'
export const UPDATE_GOODSRECEIPT = 'updateGoodsReceipt'
export const UPDATE_ANDAPPROVE_GOODSRECEIPT = 'updateAndApproveGoodsReceipt'
export const GET_GOODSRECEIPT_FROM_PO = 'getGoodsReceiptFromPO'
export const DELETE_GOODSRECEIPT = 'deleteGoodsReceipt'
// Stock Transfer actions
export const GET_STATE_STOCKTRANSFERS = 'getStateStockTransfers'
export const GET_STOCKTRANSFERS = 'getStockTransfers'
export const SEARCH_STOCKTRANSFERS = 'searchStockTransfers'
export const SORT_STOCKTRANSFERS = 'sortStockTransfers'
export const GET_STOCKTRANSFER = 'getStockTransfer'
export const CREATE_APPROVE_STOCKTRANSFER = 'createApproveStockTransfer'
export const CREATE_STOCKTRANSFER = 'createStockTransfer'
export const UPDATE_STOCKTRANSFER = 'updateStockTransfer'
export const DELETE_STOCKTRANSFER = 'deleteStockTransfer'
